package org.campagnelab.circles.publisher.mongodb.shell;

/*Generated by MPS */

import org.campagnelab.circles.publisher.db.SchemaManager;
import org.campagnelab.circles.publisher.mongodb.model.MongoDbAccess;

public class MongoDbSchemaManager extends SchemaManager {

  public void createSchema() {
    MongoDbAccess.open();
  }
  public void dropSchema() {
    MongoDbAccess.drop();
  }

}
