package org.campagnelab.circles.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class AddCirclesActions_ActionGroup extends GeneratedActionGroup {
  private static Logger LOG = LogManager.getLogger(AddCirclesActions_ActionGroup.class);
  public static final String ID = "org.campagnelab.circles.plugin.plugin.AddCirclesActions_ActionGroup";
  public AddCirclesActions_ActionGroup() {
    super("AddCirclesActions", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    try {
      AddCirclesActions_ActionGroup.this.addSeparator();
      AddCirclesActions_ActionGroup.this.addAction("org.campagnelab.circles.plugin.plugin.DropProject_Action");
      AddCirclesActions_ActionGroup.this.addAction("org.campagnelab.circles.plugin.plugin.SerializeModulesToDB_Action");
    } catch (Throwable t) {
      LOG.error("User group error", t);
    }
  }
}
