package org.campagnelab.circles.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;

public class Plugin_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("org.campagnelab.circles.plugin");
  public Plugin_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  public void createGroups() {
    // actions w/o parameters 
    addAction(new DropProject_Action());
    addAction(new SerializeModulesToDB_Action());
    // groups 
    addGroup(new AddCirclesActions_ActionGroup());
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(AddCirclesActions_ActionGroup.ID, "jetbrains.mps.ide.platform.actions.Code_ActionGroup", null);
  }
}
