package org.campagnelab.circles.plugin.plugin;

/*Generated by MPS */

import com.intellij.ui.components.JBPanel;
import javax.swing.JComponent;
import javax.swing.JTextField;
import java.awt.GridBagLayout;
import javax.swing.JLabel;
import jetbrains.mps.ide.common.LayoutUtil;

public class PublisherPageComponent extends JBPanel {
  public static JComponent create() {
    return new PublisherPageComponent();
  }
  private JTextField url;

  public PublisherPageComponent() {
    super(new GridBagLayout());

    JLabel hostname = new JLabel("Destination:");
    int i = 0;
    this.add(hostname, LayoutUtil.createLabelConstraints(++i));
    this.url = new JTextField();
    this.add(this.url, LayoutUtil.createFieldConstraints(++i));
  }
  public String getURL() {
    return url.getText();
  }
  public void setURL(String url) {
    this.url.setText(url);
  }

}
