package org.campagnelab.circles.publisher.mongodb.model;

/*Generated by MPS */


public class DatabaseStructure {
  public static final String database = "circles";
  public static final String projectsCollection = "projects";
  public static final String modulesCollection = "modules";
  public static final String modelsCollection = "models";
  public static final String nodesCollection = "root_nodes";

}
