package org.campagnelab.circles.publisher.mongodb.model;

/*Generated by MPS */


public class ModelDocument extends BaseCirclesDocument {

  public ModelDocument(String name) {
    super(name);
  }

}
