package org.campagnelab.circles.publisher.mongodb.model;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

public class ModuleDocument extends BaseCirclesDocument {

  private List<String> models;

  public ModuleDocument(String name) {
    super(name);
    models = new ArrayList<String>();
  }

  public List<String> getModels() {
    return Collections.unmodifiableList(models);
  }

  public void addModel(String modelId) {
    models.add(modelId);
    this.document.append("modelId", String.join(",", this.models));
  }

}
