package org.campagnelab.circles.publisher.mongodb.model;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

public class ModuleDocument extends BaseCirclesDocument {

  private String parentProjectId;
  private ModuleDocument.TYPE type;
  public static   enum TYPE {
    LANGUAGE() {
      public String toString() {
        return "language";
      }

    },
    SOLUTION() {
      public String toString() {
        return "solution";
      }

    },
    UNKNONWN() {
      public String toString() {
        return "unknown";
      }

    };

    public abstract String toString();
  }
  private List<String> models;

  public ModuleDocument(String name) {
    super(name);
    models = new ArrayList<String>();
  }

  public List<String> getModels() {
    return Collections.unmodifiableList(models);
  }

  public void addModel(String modelId) {
    models.add(modelId);
    this.document.append("modelId", String.join(",", this.models));
  }
  public void setParentProject(String projectId) {
    this.parentProjectId = projectId;
    this.document.append("projectId", projectId);

  }
  public String getParentProject() {
    return this.parentProjectId;
  }
  public ModuleDocument.TYPE getModuleType() {
    return this.type;
  }
  public void setModuleType(ModuleDocument.TYPE type) {
    this.type = type;
    this.document.append("type", type.toString());
  }
}
