package org.campagnelab.circles.publisher.mongodb.model;

/*Generated by MPS */

import com.mongodb.client.MongoDatabase;
import java.util.List;
import com.mongodb.ServerAddress;
import java.util.ArrayList;
import org.campagnelab.circles.publisher.db.Connection;
import com.mongodb.MongoCredential;
import com.mongodb.MongoClient;
import java.util.Arrays;

public class MongoDbAccess {

  private static MongoDatabase db;
  private static MongoDbCollection projectsCol;
  private static MongoDbCollection modulesCol;
  private static MongoDbCollection modelsCol;
  private static MongoDbCollection nodesCol;
  private static boolean open = false;

  public static MongoDatabase open() {
    List<ServerAddress> address = new ArrayList<ServerAddress>();
    address.add(new ServerAddress(Connection.hostname, Connection.port));
    MongoCredential credentials = MongoCredential.createCredential(Connection.username, DatabaseStructure.database, Connection.pwd.toCharArray());
    MongoClient mongoClient = new MongoClient(address, Arrays.asList(credentials));
    db = mongoClient.getDatabase(DatabaseStructure.database);
    createSchema(db);
    open = true;
    return db;
  }

  private static void createSchema(MongoDatabase database) {
    projectsCol = new MongoDbCollection(database, DatabaseStructure.projectsCollection);
    modulesCol = new MongoDbCollection(database, DatabaseStructure.modulesCollection);
    modelsCol = new MongoDbCollection(database, DatabaseStructure.modelsCollection);
    nodesCol = new MongoDbCollection(database, DatabaseStructure.nodesCollection);
  }

  public static MongoDbCollection getProjectsCollection() {
    if (!(open)) {
      open();
    }
    return projectsCol;
  }

  public static MongoDbCollection getModulesCollection() {
    if (!(open)) {
      open();
    }
    return modulesCol;
  }

  public static MongoDbCollection getModelsCollection() {
    if (!(open)) {
      open();
    }
    return modelsCol;
  }

  public static MongoDbCollection getNodesCollection() {
    if (!(open)) {
      open();
    }
    return nodesCol;
  }

  public static void drop() {
    if (open) {
      db.drop();
      open = false;
    }
  }

}
