package org.campagnelab.circles.publisher.mongodb.model;

/*Generated by MPS */

import com.mongodb.client.MongoDatabase;
import com.mongodb.MongoClient;
import java.util.List;
import com.mongodb.ServerAddress;
import java.util.ArrayList;
import org.campagnelab.circles.publisher.db.Connection;
import com.mongodb.MongoCredential;
import java.util.Arrays;

public class MongoDbAccess {

  private MongoDatabase db;
  private MongoClient mongoClient;
  private MongoDbCollection projectsCol;
  private MongoDbCollection modulesCol;
  private MongoDbCollection modelsCol;
  private MongoDbCollection nodesCol;
  private boolean open = false;

  public MongoDbAccess() {
    this.open();
  }

  private void open() {
    List<ServerAddress> address = new ArrayList<ServerAddress>();
    address.add(new ServerAddress(Connection.hostname, Connection.port));
    MongoCredential credentials = MongoCredential.createCredential(Connection.username, DatabaseStructure.database, Connection.pwd.toCharArray());
    mongoClient = new MongoClient(address, Arrays.asList(credentials));
    db = mongoClient.getDatabase(DatabaseStructure.database);
    createSchema();
    open = true;
  }

  private void createSchema() {
    projectsCol = new MongoDbCollection(db, DatabaseStructure.projectsCollection);
    modulesCol = new MongoDbCollection(db, DatabaseStructure.modulesCollection);
    modelsCol = new MongoDbCollection(db, DatabaseStructure.modelsCollection);
    nodesCol = new MongoDbCollection(db, DatabaseStructure.nodesCollection);
  }

  public MongoDbCollection getProjectsCollection() {
    if (!(open)) {
      open();
    }
    return projectsCol;
  }

  public MongoDbCollection getModulesCollection() {
    if (!(open)) {
      open();
    }
    return modulesCol;
  }

  public MongoDbCollection getModelsCollection() {
    if (!(open)) {
      open();
    }
    return modelsCol;
  }

  public MongoDbCollection getNodesCollection() {
    if (!(open)) {
      open();
    }
    return nodesCol;
  }

  public void drop() {
    if (!(open)) {
      open();
    }
    db.drop();
  }
  public void close() {
    if (open) {
      mongoClient.close();
      open = false;
    }
  }

}
