package org.campagnelab.circles.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.projectplugins.BaseProjectPlugin;
import java.util.List;
import jetbrains.mps.plugins.prefs.BaseProjectPrefsComponent;
import com.intellij.openapi.project.Project;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class Plugin_ProjectPlugin extends BaseProjectPlugin {
  public Plugin_ProjectPlugin() {
  }
  public List<BaseProjectPrefsComponent> createPreferencesComponents(Project project) {
    List<BaseProjectPrefsComponent> components = ListSequence.fromList(new ArrayList<BaseProjectPrefsComponent>());

    ListSequence.fromList(components).addElement(new PublisherConnection_PreferencesComponent(project));
    return components;
  }
}
