package org.campagnelab.circles.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.prefs.BaseProjectPrefsComponent;
import com.intellij.util.xmlb.annotations.Tag;
import com.intellij.openapi.project.Project;
import org.jdom.Element;
import com.intellij.util.xmlb.XmlSerializer;
import jetbrains.mps.plugins.prefs.BasePrefsPage;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import com.intellij.openapi.options.ConfigurationException;
import java.util.List;
import java.util.ArrayList;

public class PublisherConnection_PreferencesComponent extends BaseProjectPrefsComponent {
  @Tag(value = "state")
  private PublisherConnection_PreferencesComponent.MyState myState = new PublisherConnection_PreferencesComponent.MyState();
  public PublisherConnection_PreferencesComponent(Project project) {
    super(project);
  }
  public void loadState(Element state) {
    XmlSerializer.deserializeInto(this.myState, state);
    for (BasePrefsPage page : ListSequence.fromList(this.getPages())) {
      page.reset();
    }
  }
  public Element getState() {
    for (BasePrefsPage page : ListSequence.fromList(this.getPages())) {
      try {
        page.apply();
      } catch (ConfigurationException e) {
      }
    }
    return XmlSerializer.serialize(this.myState);
  }
  public PublisherConnection_PreferencesComponent.MyState getStateObject() {
    return this.myState;
  }
  public List<BasePrefsPage> createPages() {
    List<BasePrefsPage> result = ListSequence.fromList(new ArrayList<BasePrefsPage>());
    ListSequence.fromList(result).addElement(new PublisherConnection_Publisher_PreferencesPage(this.getProject(), this));
    return result;
  }
  public static class MyState {
    public String url;
    public String username;
    public String password;
    public String hostname;
    public int port;
    public MyState() {
    }
  }
}
