package org.campagnelab.circles.publisher.db;

/*Generated by MPS */


public class Connection {

  public static String hostname = "";
  public static int port = 0;
  public static String username = "";
  public static String pwd = "";


}
