package org.campagnelab.circles.publisher.db;

/*Generated by MPS */

import org.campagnelab.circles.publisher.mongodb.shell.MongoDbSchemaManager;
import org.campagnelab.circles.publisher.mongodb.shell.ModuleSerializer;

public class DbFactory {

  public static SchemaManager getSchemaManager() {
    return new MongoDbSchemaManager();
  }
  public static Serializer getSerializer() {
    return new ModuleSerializer();
  }

}
