package org.campagnelab.circles.publisher.db;

/*Generated by MPS */

import org.campagnelab.circles.publisher.mongodb.MongoDbSchemaManager;

public class DbFactory {

  protected static SchemaManager getGenerator() {
    return new MongoDbSchemaManager();
  }
}
