package org.campagnelab.circles.publisher.db;

/*Generated by MPS */

import jetbrains.mps.project.MPSProject;
import java.util.List;
import org.jetbrains.mps.openapi.module.SModule;

public class ModuleSerializer {

  public static void serializeProjectWithModules(MPSProject project, List<SModule> modules) {
    createDb(project);
  }
  public static void dropDb(MPSProject project) {
    DbFactory.getGenerator().dropSchema();
  }
  public static void createDb(MPSProject project) {
    DbFactory.getGenerator().createSchema();
  }
}
