package org.campagnelab.circles.publisher.db;

/*Generated by MPS */

import org.campagnelab.mps.editor2pdf.behavior.SVGWriter;
import org.campagnelab.circles.publisher.mongodb.RootNodeDocument;
import org.campagnelab.circles.publisher.mongodb.MongoDbCollection;

public class NodeWriter implements SVGWriter {
  private final RootNodeDocument node;
  private final MongoDbCollection parentCollection;

  public NodeWriter(RootNodeDocument node, MongoDbCollection parentCollection) {
    this.node = node;
    this.parentCollection = parentCollection;
  }

  public void write(String svgFragment) {
    this.node.setSvgFragment(svgFragment);
  }
  public void append(String svgFragment) {
    this.node.setSvgFragment(svgFragment);
  }
  public void close() {
    parentCollection.addDocument(this.node.toDoc());
  }
  @Override
  public String toString() {
    return this.node.getSvgFragment();
  }
}
