package org.campagnelab.circles.publisher.mongodb;

/*Generated by MPS */


public class Configuration {

  /*package*/ static final String hostname = "localhost";
  /*package*/ static final int port = 27017;
  /*package*/ static final String username = "admin";
  /*package*/ static final String pwd = "";
  /*package*/ static final String database = "circles";
  public static final String projectsCollection = "projects";
  public static final String modulesCollection = "modules";
  public static final String modelsCollection = "models";
  public static final String nodesCollection = "root_nodes";


}
