package org.campagnelab.circles.publisher.mongodb;

/*Generated by MPS */


public class Configuration {

  /*package*/ static final String hostname = "localhost";
  /*package*/ static final int port = 27017;
  /*package*/ static final String username = "admin";
  /*package*/ static final String pwd = "";
  /*package*/ static final String database = "circles";
  /*package*/ static final String projectCollection = "projects";
  /*package*/ static final String moduleCollection = "modules";
  /*package*/ static final String modelCollection = "models";
  /*package*/ static final String nodeCollection = "root_nodes";


}
