package org.campagnelab.circles.publisher.mongodb;

/*Generated by MPS */

import org.campagnelab.circles.publisher.db.SchemaManager;
import com.mongodb.client.MongoDatabase;

public class MongoDbSchemaManager extends SchemaManager {


  public void createSchema() {
    MongoDatabase database = MongoDbAccess.open();
    new MongoDbCollection(database, Configuration.projectCollection);
    new MongoDbCollection(database, Configuration.moduleCollection);
    new MongoDbCollection(database, Configuration.modelCollection);
    new MongoDbCollection(database, Configuration.nodeCollection);
  }
  public void dropSchema() {
    MongoDbAccess.drop(MongoDbAccess.open());
  }
}
