package org.campagnelab.circles.publisher.mongodb;

/*Generated by MPS */

import org.campagnelab.circles.publisher.db.SchemaManager;
import com.mongodb.client.MongoDatabase;

public class MongoDbSchemaManager extends SchemaManager {


  public void createSchema() {
    MongoDatabase database = MongoDbAccess.open();
    new MongoDbCollection(database, Configuration.projectsCollection);
    new MongoDbCollection(database, Configuration.modulesCollection);
    new MongoDbCollection(database, Configuration.modelsCollection);
    new MongoDbCollection(database, Configuration.nodesCollection);
  }
  public void dropSchema() {
    MongoDbAccess.drop(MongoDbAccess.open());
  }
}
