package org.campagnelab.circles.publisher.mongodb;

/*Generated by MPS */


public class RootNodeDocument extends BaseCirclesDocument {

  private String svgRendering;
  private String modelId;
  public RootNodeDocument() {
    super();
  }
  public RootNodeDocument(String name) {
    super(name);
  }
  public String getSvgRendering() {
    return svgRendering;
  }
  public void setSvgRendering(String svgRendering) {
    this.svgRendering = svgRendering;
    this.document.append("SVG", svgRendering);
  }
  public String getModelId() {
    return modelId;
  }
  public void setModelId(String modelId) {
    this.modelId = modelId;
    this.document.append("modelId", modelId);
  }

}
